name: Get changed directories
description: Get a list of unique directories that were changed in the latest commit.
runs:
  using: composite
  steps:
    - name: Get changed directories
      shell: bash
      run: |
        PROJECTS_DIR="projects"
        echo "$ branch"
        git branch
        echo "$ git rev-parse HEAD"
        git rev-parse HEAD
        echo "$ git log -1"
        git log -1
        echo "$ status"
        git status
        echo "> diff"
        git diff --name-only HEAD HEAD~1
        echo ""

        # 最新のコミットとその1つ前のコミットの差分を取得
        git diff --name-only HEAD HEAD~1 | \
        # projects配下のファイルのディレクトリ名を取得
        awk -F/ -v dir="$PROJECTS_DIR" '$1 == dir {print $2}' | \
        # 重複を取り除く
        sort -u > changed_dirs.txt

        echo "> changes"
        cat changed_dirs.txt
        echo ""
