name: Get changed directories
description: "Get a list of unique directories that were changed in the latest commit."
runs:
  using: composite
  steps:
    - name: Get changed directories
      shell: bash
      run: |
        set -x
        projects_dir="projects"

        # 最新のコミットとその1つ前のコミットの差分を取得し、
        # 変更されたファイルがどのプロジェクトに属するかをファイルに出力
        echo "projects_dir: $projects_dir"
        git diff --name-only HEAD HEAD~1
        git diff --name-only HEAD HEAD~1 | grep '^${projects_dir}/'
        git diff --name-only HEAD HEAD~1 | grep '^${projects_dir}/' | awk -F/ '{print $2}
