name: Get changed directories
description: "Get a list of unique directories that were changed in the latest commit."
runs:
  using: composite
  steps:
    - name: Get changed directories
      shell: bash
      run: |
        echo "a" | grep a | awk -F/ '{print $1}'
        echo "-"
        echo "a" | grep z | awk -F/ '{print $1}'
        echo "--"
