version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/projects/portfolio"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
    groups:
      portfolio-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "bun"
    directory: "/projects/file-server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
    groups:
      file-server-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "uv"
    directory: "/projects/edit-vid"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
    groups:
      edit-vid-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "uv"
    directory: "/projects/simple-agent-poc"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
    groups:
      simple-agent-poc-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
