[project]
name = "python-uv-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.9",
    "uvicorn[standard]>=0.34.0",
]
