@apiKey={{$dotenv GEMINI_API_KEY}}
@model=gemini-2.0-flash
@baseURL=https://generativelanguage.googleapis.com/v1beta/openai
@uploadImage={{$dotenv UPLOAD_IMAGE}}

### Chat Completions：通常応答
POST {{ baseURL }}/chat/completions
Content-Type: application/json
Authorization: Bearer {{ apiKey }}

{
  "model": "{{ model }}",
  "messages": [
    {
      "role": "user",
      "content": "who are you?"
    }
  ]
}

### Chat Completions：ストリーミング
POST {{ baseURL }}/chat/completions
Content-Type: application/json
Authorization: Bearer {{ apiKey }}

{
  "model": "{{ model }}",
  "messages": [
    {
      "role": "user",
      "content": "who are you?"
    }
  ],
  "stream": true,
  "stream_options": { "include_usage": true }
}

### Chat Completions：画像入力
POST {{ baseURL }}/chat/completions
Content-Type: application/json
Authorization: Bearer {{ apiKey }}

{
  "model": "{{ model }}",
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "What is this image?"
        },
        {
          "type": "image_url",
          "image_url": {
            "url": "{{ uploadImage }}"
          }
        }
      ]
    }
  ]
}
