@apiKey={{$dotenv OPENAI_API_KEY}}
@model=gpt-4o-mini
@baseURL=https://api.openai.com/v1
@uploadImage={{$dotenv UPLOAD_IMAGE}}

#### chat/completions
POST {{ baseURL }}/chat/completions
Content-Type: application/json
Authorization: Bearer {{ apiKey }}

{
  "model": "{{ model }}",
  "messages": [
    {
      "role": "user",
      "content": "who are you?"
    }
  ]
}

#### chat/completions - stream
POST {{ baseURL }}/chat/completions
Content-Type: application/json
Authorization: Bearer {{ apiKey }}

{
  "model": "{{ model }}",
  "messages": [
    {
      "role": "user",
      "content": "who are you?"
    }
  ],
  "stream": true,
  "stream_options": { "include_usage": true }
}

#### chat/completions with image
POST {{ baseURL }}/chat/completions
Content-Type: application/json
Authorization: Bearer {{ apiKey }}

{
  "model": "{{ model }}",
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "What is this image?"
        },
        {
          "type": "image_url",
          "image_url": {
            "url": "{{ uploadImage }}"
          }
        }
      ]
    }
  ]
}

### chat/completions - websearch
POST {{ baseURL }}/chat/completions
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "model": "gpt-4o-mini-search-preview",
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "今日の「Yahoo!ニュース」で１つ内容をピックアップして"
        }
      ],
      "web_search_options": {
        "search_context_size": "low",
        "user_location": {
          "type": "approximate",
          "approximate": {
            "country": "JP"
          }
        }
      }
    }
  ]
}
