@apiKey={{$dotenv XAI_API_KEY}}
@model=grok-2-latest
@baseURL=https://api.x.ai/v1
@uploadImage={{$dotenv UPLOAD_IMAGE}}

### Chat Completions：通常応答
POST {{ baseURL }}/chat/completions
Content-Type: application/json
Authorization: Bearer {{ apiKey }}

{
  "model": "{{ model }}",
  "messages": [
    {
      "role": "user",
      "content": "who are you?"
    }
  ]
}

### Chat Completions：ストリーミング
POST {{ baseURL }}/chat/completions
Content-Type: application/json
Authorization: Bearer {{ apiKey }}

{
  "model": "{{ model }}",
  "messages": [
    {
      "role": "user",
      "content": "who are you?"
    }
  ],
  "stream": true,
  "stream_options": { "include_usage": true }
}

### Chat Completions：画像入力（非対応）
POST {{ baseURL }}/chat/completions
Content-Type: application/json
Authorization: Bearer {{ apiKey }}

{
  "model": "{{ model }}",
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "What is this image?"
        },
        {
          "type": "image_url",
          "image_url": {
            "url": "{{ uploadImage }}"
          }
        }
      ]
    }
  ]
}
