@apiKey={{$dotenv DEEPSEEK_API_KEY}}
@model=deepseek-chat
@baseURL=https://api.deepseek.com
@uploadImage={{$dotenv UPLOAD_IMAGE}}

#### chat/completions
POST {{ baseURL }}/chat/completions
Content-Type: application/json
Authorization: Bearer {{ apiKey }}

{
  "model": "{{ model }}",
  "messages": [
    {
      "role": "user",
      "content": "日本の首都は"
    }
  ]
}

#### chat/completions - stream
POST {{ baseURL }}/chat/completions
Content-Type: application/json
Authorization: Bearer {{ apiKey }}

{
  "model": "{{ model }}",
  "messages": [
    {
      "role": "user",
      "content": "日本の首都は"
    }
  ],
  "stream": true,
  "stream_options": { "include_usage": true }
}

#### chat/completions with image (※画像の読み込みはサポートしていない）
POST {{ baseURL }}/chat/completions
Content-Type: application/json
Authorization: Bearer {{ apiKey }}

{
  "model": "{{ model }}",
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "この画像は何ですか？"
        },
        {
          "type": "image_url",
          "image_url": {
            "url": "{{ uploadImage }}"
          }
        }
      ]
    }
  ]
}
