/** DTO の正は server/src/schema.ts。ここは再配布だけで、hooks / components の import 先を保つ。 */
import type { EventEntry } from "server";

export type {
  AgentDef,
  AgentPayloadInfo,
  AgentSkillInfo,
  AgentSuggestion,
  ArchiveSettingsResponse,
  BuiltinSkillInfo,
  Catalog,
  CatalogResponse,
  ChatMessage,
  CompactionInfo,
  CompactionReason,
  ContextUsage,
  CreateAgentBody,
  CreateSkillBody,
  EventEntry,
  FileDownloadCheck,
  FileEntry,
  FileListing,
  FilePreview,
  FileRename,
  FileSkillInfo,
  FileSkillsResponse,
  Health,
  MessageMetrics,
  ModelDiagnosticStatus,
  ModelMutationError,
  ModelMutationResponse,
  ModelReferenceDiagnostic,
  ModelOption,
  ModelRef,
  ModelsSettingsResponse,
  NotificationMention,
  NotificationResult,
  NotificationsResponse,
  PostMessageResult,
  Project,
  ProjectsResponse,
  ProviderAuthSetting,
  RuntimeAuth,
  RuntimeAuthSource,
  RuntimeCatalogModel,
  RuntimeCatalogProvider,
  RuntimeDiagnosticSummary,
  RuntimeEnvironmentResponse,
  RuntimeEnvironmentState,
  RuntimeModelsResponse,
  RuntimeProviderSummary,
  RuntimeVersions,
  RunPayload,
  RunStatus,
  SandboxRuntimeCommand,
  SandboxRuntimeEnvironment,
  SessionCompactionResult,
  SessionNotifyResponse,
  SessionPayload,
  SessionSkillInfo,
  SessionSkillsPreview,
  SessionSkillsResponse,
  SessionSummary,
  SkillDef,
  SkillLoad,
  StopResult,
  ThinkingLevel,
  ToolCall,
  UpdateAgentBody,
  UpdateArchiveSettingsBody,
  UpdateNotificationsBody,
  UpdateProviderKeyBody,
  UpdateSkillBody,
  Usage,
} from "server";

/** SSE で受ける型名。ping はサーバーが送る生存確認で、状態には流さない (server の EventEntry には現れない) */
export type SSEEventType = EventEntry["type"] | "ping";
