networks:
  default:
    name: home_network

services:
  dozzle:
    container_name: dozzle
    image: ghcr.io/amir20/dozzle:latest
    restart: always
    ports:
      - 8888:8080
    environment:
      DOZZLE_ENABLE_SHELL: true
      DOZZLE_ENABLE_ACTIONS: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
