networks:
  default:
    name: home_network

services:
  file-server:
    container_name: file-server
    image: ghcr.io/u7chan/monorepo/file-server:${PROJECT_IMAGE_TAG:-latest}
    restart: always
    ports:
      - 8010:3000
    environment:
      - AUTH_DIR=/app/auth
    volumes:
      - file-server:/app/uploads
      - file-server-auth:/app/auth

volumes:
  file-server:
  file-server-auth:
