networks:
  default:
    name: home_network

services:
  mcp-inspector:
    container_name: mcp-inspector
    image: ghcr.io/u7chan/monorepo/mcp-inspector:latest
    restart: always
    ports:
      - 6274:6274
