networks:
  default:
    name: home_network

services:
  portfolio:
    container_name: portfolio
    image: ghcr.io/u7chan/monorepo/portfolio:latest
    restart: always
    ports:
      - 8000:3000
    env_file:
      - .env.secret
    environment:
      SERVER_PORT: 3000

  portfolio-db:
    container_name: portfolio-db
    image: postgres:17-alpine
    restart: always
    ports:
      - 7000:5432
    env_file:
      - .env.secret
    volumes:
      - portfolio-db-data:/var/lib/postgresql/data

volumes:
  portfolio-db-data:
