services:
  portfolio:
    container_name: portfolio
    image: ghcr.io/u7chan/monorepo/portfolio:latest
    restart: always
    ports:
      - 8000:3000
    environment:
      - OPENAI_API_KEY
      - DEEPSEEK_API_KEY

  llm-wrapper-api:
    container_name: llm-wrapper-api
    image: ghcr.io/u7chan/monorepo/llm-wrapper-api:latest
    restart: always
    ports:
      - 8001:8000
