services:
  portfolio:
    container_name: portfolio
    image: ghcr.io/u7chan/monorepo/portfolio:latest
    restart: always
    ports:
      - 8000:3000
    env_file:
      - .env

  llm-wrapper-api:
    container_name: llm-wrapper-api
    image: ghcr.io/u7chan/monorepo/llm-wrapper-api:latest
    restart: always
    ports:
      - 8001:8000
    env_file:
      - .env
