name: Build Docker Images
description: Building the Dockerfiles for multiple projects.
inputs:
  stage:
    description: "Docker build arguments --target option"
    required: true
runs:
  using: composite
  steps:
    - name: Build Docker Images
      shell: bash
      run: |
        PROJECTS_DIR="projects"

        # BUILD_PROJECTが指定されているかチェック
        if [ -z "${{ env.BUILD_PROJECT }}" ]; then
          echo "Error: BUILD_PROJECT is not set."
          exit 1
        fi

        IFS=',' read -ra BUILD_PROJECT_ARRAY <<< "${{ env.BUILD_PROJECT }}"
        echo "Build project count: ${#BUILD_PROJECT_ARRAY[@]}"

        COMMIT_HASH=$(git rev-parse --short HEAD)

        for project in "${BUILD_PROJECT_ARRAY[@]}"; do
          GHCR_URI=ghcr.io/${{ github.repository }}/$project:latest
          PROJECT_DIR=$PROJECTS_DIR/$project
          DOCKER_FILE=$PROJECT_DIR/Dockerfile
          SEARCH_KEYWORD="AS ${{ inputs.stage }}"
          PREBUILD_SCRIPT="$PROJECT_DIR/pre-docker-build.sh"

          echo "GHCR_URI: $GHCR_URI"
          echo "PROJECT_DIR: $PROJECT_DIR"
          echo "DOCKER_FILE: $DOCKER_FILE"
          echo "SEARCH_KEYWORD: $SEARCH_KEYWORD"

          if [ -e "$PREBUILD_SCRIPT" ]; then
            echo "Running pre-build script: $PREBUILD_SCRIPT"
            cd "$PROJECT_DIR"
            sh "$PREBUILD_SCRIPT"
            cd -
          fi

          if grep -q "$SEARCH_KEYWORD" "$DOCKER_FILE" 2>/dev/null; then
            echo "Found starge: ${{ inputs.stage }}"
            docker build --build-arg COMMIT_HASH=$COMMIT_HASH -t $GHCR_URI --target=${{ inputs.stage }} $PROJECT_DIR
          else
            echo "Not found starge: ${{ inputs.stage }}"
            docker build --build-arg COMMIT_HASH=$COMMIT_HASH -t $GHCR_URI $PROJECT_DIR
          fi
        done
