name: Build Docker Images
description: Build Docker images for projects with Dockerfile

inputs:
  stage:
    description: "Docker build arguments --target option"
    required: true

runs:
  using: composite
  steps:
    - name: Build Docker Images
      shell: bash
      run: |
        # 共通スクリプトを実行
        ${{ github.action_path }}/build-docker-images.sh "${{ inputs.stage }}"
