services:
  portfolio:
    container_name: portfolio
    build:
      context: ../../projects/portfolio
    ports:
      - 8000:3000
    env_file:
      - .env

  llm-wrapper-api:
    container_name: llm-wrapper-api
    build:
      context: ../../projects/llm-wrapper-api
    ports:
      - 8001:8000
    env_file:
      - .env
