services:
  portfolio:
    container_name: portfolio
    build:
      context: ../../projects/portfolio
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env

  llm-wrapper-api:
    container_name: llm-wrapper-api
    build:
      context: ../../projects/llm-wrapper-api
    restart: always
    ports:
      - 3001:8000
    env_file:
      - .env
